---
- name: Install Node.js binary package https://github.com/nodejs/help/wiki/Installation
  block:

    - name: Remove Node.js APT package
      ansible.builtin.apt:
        pkg:
          - nodejs
        state: absent

    - name: Check the latest version of Node.js
      block:

        - name: Check the latest version of Node.js
          ansible.builtin.uri:
            url: https://github.com/nodejs/node/releases/latest
            method: HEAD
            status_code: 302
            follow_redirects: none
          check_mode: false
          changed_when: false
          register: nodejs_headers

        - name: Debug Node.js latest headers
          ansible.builtin.debug:
            msg:
              - "Location: {{ nodejs_headers.location }}"
              - "Path: {{ nodejs_headers.location | urlsplit('path') }}"
              - "Version: {{ nodejs_headers.location | urlsplit('path') | basename | regex_replace('^v') | string }}"
            verbosity: 2

        - name: Set a fact for the latest version of Node.js
          ansible.builtin.set_fact:
            nodejs_version_latest: "{{ nodejs_headers.location | urlsplit('path') | basename | regex_replace('^v') | string }}"

      when: nodejs_version == "latest"

    - name: Set a fact for the required version of Node.js
      ansible.builtin.set_fact:
        nodejs_version_required: "{% if nodejs_version == 'latest' %}{{ nodejs_version_latest }}{% else %}{{ nodejs_version }}{% endif %}"

    - name: Node.js GPG keys present
      ansible.builtin.include_tasks: gpg_recv_key.yml
      loop: "{{ nodejs_release_keys }}"
      loop_control:
        loop_var: fpr

    - name: Node.js download directory present
      ansible.builtin.file:
        path: "{{ nodejs_download_path }}"
        state: directory
        mode: 0700
        owner: root
        group: root

    - name: Node.js SHA256SUMS sig present
      ansible.builtin.get_url:
        url: "https://nodejs.org/dist/v{{ nodejs_version_required }}/SHASUMS256.txt.sig"
        dest: "{{ nodejs_download_path }}/SHASUMS256.txt.sig"
        mode: 0644
        owner: root
        group: root

    - name: Node.js SHA256SUMS present
      ansible.builtin.get_url:
        url: "https://nodejs.org/dist/v{{ nodejs_version_required }}/SHASUMS256.txt"
        dest: "{{ nodejs_download_path }}/SHASUMS256.txt"
        mode: 0644
        owner: root
        group: root

    - name: Download Node.js binary
      ansible.builtin.get_url:
        url: "https://nodejs.org/dist/v{{ nodejs_version_required }}/node-v{{ nodejs_version_required }}-linux-x64.tar.gz"
        dest: "{{ nodejs_download_path }}/node-v{{ nodejs_version_required }}-linux-x64.tar.gz"
        mode: 0644
        owner: root
        group: root

    - name: Node.js SHA256SUMS GPG signature checked
      ansible.builtin.shell: |
        set -e -o pipefail
        grep node-v{{ nodejs_version_required }}-linux-x64.tar.gz SHASUMS256.txt | sha256sum -c -
      args:
        executable: "{{ ansible_local.bash.path }}"
        chdir: "{{ nodejs_download_path }}"

    - name: Node.js lib directory absent
      ansible.builtin.file:
        path: /usr/local/lib/nodejs
        state: absent

    - name: Node.js lib directory present
      ansible.builtin.file:
        path: /usr/local/lib/nodejs
        state: directory
        mode: 0755
        owner: root
        group: root

    - name: Node.js binary package unarchived
      ansible.builtin.unarchive:
        src: "{{ nodejs_download_path }}/v{{ nodejs_version_required }}-linux-x64.tar.gz"
        dest: /usr/local/lib/nodejs
        remote_src: true

    - name: Test node version
      ansible.builtin.command: ./node -v
      args:
        chdir: "/usr/local/lib/nodejs/node-v{{ nodejs_version_required }}-linux-x64/bin"

    - name: Test npm version
      ansible.builtin.command: ./npm version
      args:
        chdir: "/usr/local/lib/nodejs/node-v{{ nodejs_version_required }}-linux-x64/bin"

    - name: Test node version
      ansible.builtin.command: ./npx -v
      args:
        chdir: "/usr/local/lib/nodejs/node-v{{ nodejs_version_required }}-linux-x64/bin"

    - name: Node.js symlinks present
      ansible.builtin.file:
        src: "{{ file.src }}"
        dest: "{{ file.dest }}"
        follow: false
        mode: 0777
        owner: root
        group: root
      loop:
        - src: "/usr/local/lib/nodejs/node-v{{ nodejs_version_required }}-linux-x64/bin/node"
          dest: "/usr/local/bin/node"
        - src: "/usr/local/lib/nodejs/node-v{{ nodejs_version_required }}-linux-x64/bin/node"
          dest: "/usr/local/bin/nodejs"
        - src: "/usr/local/lib/nodejs/node-v{{ nodejs_version_required }}-linux-x64/bin/npm"
          dest: "/usr/local/bin/npme"
        - src: "/usr/local/lib/nodejs/node-v{{ nodejs_version_required }}-linux-x64/bin/npx"
          dest: "/usr/local/bin/npx"

    - name: Install additional Node.js packages
      community.general.npm:
        name: "{{ pkg }}"
        global: true
      loop: "{{ nodejs_packages }}"
      loop_control:
        loop_var: pkg
      when: ( nodejs_packages is defined ) and ( nodejs_packages != [] )

  tags:
    - nodejs
...
