# Copyright 2020-2024 Chris Croome
#
# This file is part of the Webarchitects Node.js Ansible role.
#
# The Webarchitects Node.js Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Node.js Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Node.js Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Node.js GPG keys present
  ansible.builtin.command: "gpg --keyserver hkps://keys.openpgp.org --recv-keys {{ nodejs_fpr }}"
  register: nodejs_recv_key
  changed_when:
    - ( "not changed" not in nodejs_recv_key.stderr )
    - ( "skipped" not in nodejs_recv_key.stderr )
  tags:
    - nodejs
...
