# Copyright 2020-2023 Chris Croome
#
# This file is part of the Webarchitects Node.js Ansible role.
#
# The Webarchitects Node.js Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Node.js Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Node.js Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Ansible apt local facts
  block:

    - name: Required packages present
      ansible.builtin.apt:
        pkg:
          - jo
        state: present

    - name: Ansible facts.d directory present
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        recurse: true
        state: directory
        mode: 0755
        owner: root
        group: root

    - name: Ansible local facts scripts present
      ansible.builtin.template:
        src: "{{ script }}.j2"
        dest: "/etc/ansible/facts.d/{{ script }}"
        mode: 0755
        owner: root
        group: root
      loop:
        - dpkg.fact
        - gpg.fact
        - bash.fact
      loop_control:
        loop_var: script

    - name: Re-read Ansible local facts
      ansible.builtin.setup:
        filter: ansible_local

    - name: Check that ansible_local facts are defined
      ansible.builtin.assert:
        that:
          - ansible_local.dpkg is defined
          - ansible_local.gpg is defined
          - ansible_local.bash is defined

    - name: Print Ansible local dpkg facts
      ansible.builtin.debug:
        var: ansible_local.dpkg
        verbosity: 2

    - name: Print Ansible local gpg facts
      ansible.builtin.debug:
        var: ansible_local.gpg
        verbosity: 2

    - name: Print Ansible local bash facts
      ansible.builtin.debug:
        var: ansible_local.bash
        verbosity: 2

  tags:
    - nodejs
    - nodejs_apt
    - nodejs_apt_local_facts
...
