# Copyright 2018-2026 Chris Croome
#
# This file is part of the Webarchitects Node.js Ansible role.
#
# The Webarchitects Node.js Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Node.js Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Node.js Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
argument_specs:
  main:
    short_description: The main entry point for the nodejs role.
    options:
      nodejs_apt_cache_show_nodejs:
        type: dict
        required: false
        description: Results from running apt-cache show nodejs using the ansible.builtin.command module.
      nodejs_apt_cache_show:
        type: list
        required: false
        description: Results from JC converting apt-cache show nodejs results into a list.
      nodejs_installed:
        type: int
        required: false
        description: Interger for the installed nodejs version.
      nodejs_sources_contents:
        type: dict
        required: false
        description: Results form running the ansible.builtin.slurp module.
      nodejs_sources_contents_prior:
        type: dict
        required: false
        description: Contents of the node.sources file in JSON format.
      nodejs_asc_file:
        type: dict
        required: false
        description: Results form running the ansible.builtin.stat module.
      nodejs_gpg:
        type: dict
        required: false
        description: Results form running the ansible.builtin.command module.
      nodejs_gpg_asc_file:
        type: dict
        required: false
        description: Results form running the ansible.builtin.get_url module.
      nodejs_gpg_file:
        type: dict
        required: false
        description: Results form running the ansible.builtin.stat module.
      nodejs_installed_check:
        type: dict
        required: false
        description: Results form running the ansible.builtin.command module.
      nodejs_nodesource_gpg_fingerprints_found:
        type: list
        elements: str
        required: false
        description: List of GPG fingerprints.
      nodejs_old_apt_list_files:
        type: dict
        required: false
        description: Results form running the ansible.builtin.find module.
      nodejs_path_check:
        type: dict
        required: false
        description: Results form running the ansible.builtin.stat module.
      nodejs_preferences:
        type: dict
        required: false
        description: Results form running the ansible.builtin.template module.
      nodejs_sources:
        type: dict
        required: false
        description: Results form running the ansible.builtin.deb822_repository module.
      nodejs_sources_check:
        type: dict
        required: false
        description: Results form running the ansible.builtin.deb822_repository module.
      nodejs_sources_contents_b64encoded:
        type: dict
        required: false
        description: Results form running the ansible.builtin.slurp module.
      nodejs_sources_path:
        type: dict
        required: false
        description: Results form running the ansible.builtin.stat module.
      nodejs_argument_spec:
        type: dict
        required: true
        description: Argument spec dictionary.
      nodejs_combined_argument_spec:
        type: dict
        required: true
        description: Internal combined argument spec dictionary.
      nodejs_internal_argument_spec:
        type: dict
        required: true
        description: Internal argument spec dictionary.
      nodejs_nodesource_gpg_checksum:
        type: str
        required: true
        description: Internal string for the Node.js GPG key SHA256 checksum.
      nodejs_nodesource_gpg_fingerprints:
        type: list
        elements: str
        required: true
        description: Internal list of Node.js GPG key fingerprints.
      nodejs_nodesource_gpg_url:
        type: str
        required: true
        description: Internal string for the Node.js GPG URL.
      nodejs_nodesource_pkg:
        type: list
        elements: str
        required: true
        description: Internal list of packages that can be installed from the Node.js repo.
      nodejs_release_keys:
        type: list
        elements: str
        required: true
        description: Internal list of Node.js GPG release key fingerprints.
...
